# SPDX-FileCopyrightText: 2026 Arcangelo Massari <arcangelo.massari@unibo.it>
#
# SPDX-License-Identifier: ISC

from collections.abc import Iterable, Iterator

from triplelite._types import RDFTerm

class TripleLite:
    identifier: str | None
    def __init__(self, identifier: str | None = None, reverse_index_predicates: frozenset[str] | None = None) -> None: ...
    def add(self, triple: tuple[str, str, RDFTerm]) -> None: ...
    def add_many(self, triples: Iterable[tuple[str, str, RDFTerm]]) -> None: ...
    def remove(self, triple: tuple[str | None, str | None, RDFTerm | None]) -> None: ...
    def triples(self, pattern: tuple[str | None, str | None, RDFTerm | None]) -> Iterator[tuple[str, str, RDFTerm]]: ...
    def objects(self, subject: str | None = None, predicate: str | None = None) -> Iterator[RDFTerm]: ...
    def predicate_objects(self, subject: str | None = None) -> Iterator[tuple[str, RDFTerm]]: ...
    def subjects(self, predicate: str | None = None, object: RDFTerm | None = None) -> Iterator[str]: ...
    def has_subject(self, subject: str) -> bool: ...
    def __contains__(self, triple: tuple[str, str, RDFTerm]) -> bool: ...
    def __iter__(self) -> Iterator[tuple[str, str, RDFTerm]]: ...
    def __len__(self) -> int: ...
